---
apiVersion: v1
baseDomain: clamie.au
metadata:
  name: sno-fips
fips: true
networking:
  networkType: OVNKubernetes
  machineNetwork:
    - cidr: 10.120.20.0/24
  clusterNetwork:
    - cidr: 10.128.0.0/14
      hostPrefix: 23
  serviceNetwork:
    - 172.30.0.0/16
controlPlane:
  name: master
  replicas: 1  # SNO
  hyperthreading: Enabled
compute:
  - name: worker
    replicas: 0
    hyperthreading: Enabled
platform:
  none: {}
# Cannot set SNO platform type to baremetal.
#  baremetal:
#    apiVIPs:
#      - 10.120.20.60
#    ingressVIPs:
#      - 10.120.20.61
pullSecret: 'REPLACE_ME'
sshKey: 'REPLACE_ME'