---
all:
  hosts:
    infra-node-01.clam.lan:
      ansible_host: 192.168.30.10

    idm-master-01.clam.lan:
      ansible_host: 192.168.30.2

virtual:
  hosts:
    idm-master-01.clam.lan:

nodes:
  hosts:
    infra-node-01.clam.lan:

ipaserver:
  hosts:
    idm-master-01.clam.lan:
