apiVersion: v1alpha1
kind: AgentConfig
metadata:
  name: ocp
rendezvousIP: 192.168.40.11
additionalNTPSources:
  - 192.168.30.2
hosts:
  - hostname: node-01
    role: master
    rootDeviceHints:
      deviceName: "/dev/nvme0n1"
    interfaces:
      - name: enp2s0
        macAddress: 00:e0:4c:68:0c:07
    networkConfig:
      interfaces:
        - name: enp2s0
          type: ethernet
          state: up
          mac-address: 00:e0:4c:68:0c:07
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: 192.168.40.11
                prefix-length: 27
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.40.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.40.1
            next-hop-interface: enp2s0
            table-id: 254

  - hostname: node-02
    role: master
    rootDeviceHints:
      deviceName: "/dev/nvme0n1"
    interfaces:
      - name: enp2s0
        macAddress: 00:e0:4c:68:0b:c9
    networkConfig:
      interfaces:
        - name: enp2s0
          type: ethernet
          state: up
          mac-address: 00:e0:4c:68:0b:c9
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: 192.168.40.12
                prefix-length: 27
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.40.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.40.1
            next-hop-interface: enp2s0
            table-id: 254

  - hostname: node-03
    role: master
    rootDeviceHints:
      deviceName: "/dev/nvme0n1"
    interfaces:
      - name: enp2s0
        macAddress: 00:e0:4c:68:10:75
    networkConfig:
      interfaces:
        - name: enp2s0
          type: ethernet
          state: up
          mac-address: 00:e0:4c:68:10:75
          ipv4:
            enabled: true
            dhcp: false
            address:
              - ip: 192.168.40.13
                prefix-length: 27
          ipv6:
            enabled: false
      dns-resolver:
        config:
          server:
            - 192.168.40.1
      routes:
        config:
          - destination: 0.0.0.0/0
            next-hop-address: 192.168.40.1
            next-hop-interface: enp2s0
            table-id: 254
