---
- name: Install IPA client
  hosts: ipaclients
  become: true
  vars_files:
    - idm_secrets.yml
  pre_tasks:
    - name: Set FQDN
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
        use: systemd 
    
    - name: Allow local network to access NTP server.
      ansible.builtin.lineinfile:
        path: /etc/hosts
        line: "{{ hostvars['idm.clamie.au'].ansible_host }} {{ hostvars['idm.clamie.au'].inventory_hostname }}"
        regexp: "^{{ hostvars['idm.clamie.au'].ansible_host }}"
        state: present
        
  roles:
    - role: freeipa.ansible_freeipa.ipaclient

